CREATE SCHEMA IF NOT EXISTS clean_data;

CREATE TABLE IF NOT EXISTS clean_data.diabetic_clean (
  encounter_id              BIGINT PRIMARY KEY,
  patient_nbr               BIGINT,
  race                      TEXT,
  gender                    TEXT CHECK (gender IN ('Male','Female','Unknown/Invalid','Other')),
  age_bucket                TEXT,
  time_in_hospital          INT,
  num_lab_procedures        INT,
  num_procedures            INT,
  num_medications           INT,
  number_outpatient         INT,
  number_emergency          INT,
  number_inpatient          INT,
  number_diagnoses          INT,
  max_glu_serum             TEXT,
  a1c_result                TEXT,
  insulin                   TEXT,
  change_med                BOOLEAN,
  diabetes_med              BOOLEAN,
  readmitted_label          TEXT,
  diag_1                    TEXT,
  diag_2                    TEXT,
  diag_3                    TEXT,
  medical_specialty         TEXT,
  admission_type_id         INT,
  discharge_disposition_id  INT,
  admission_source_id       INT,
  outcome                   INT,
  batch_id                  INT,
  split                     TEXT
);