name: 'Build and Push Docker Image'
description: 'Reusable action to build and push Docker images to DockerHub'
inputs:
  service-name:
    description: 'Name of the service (e.g., api, streamlit)'
    required: true
  context:
    description: 'Build context path'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-token:
    description: 'DockerHub token'
    required: true
  push:
    description: 'Whether to push the image'
    required: false
    default: 'true'
  tags:
    description: 'Comma-separated list of tags'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      shell: bash

    - name: Log in to Docker Hub
      if: inputs.push == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
      shell: bash

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        cache-from: type=registry,ref=${{ inputs.dockerhub-username }}/diabetic-${{ inputs.service-name }}:buildcache
        cache-to: type=registry,ref=${{ inputs.dockerhub-username }}/diabetic-${{ inputs.service-name }}:buildcache,mode=max
        platforms: linux/amd64
      shell: bash

